// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	token0 "github.com/ilijamt/vault-plugin-secrets-gitlab/internal/model/token"
	"github.com/ilijamt/vault-plugin-secrets-gitlab/internal/token"
	mock "github.com/stretchr/testify/mock"
	gitlab "gitlab.com/gitlab-org/api/client-go"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateGroupAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateGroupAccessToken(ctx context.Context, groupId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel) (*token0.TokenGroup, error) {
	ret := _mock.Called(ctx, groupId, name, expiresAt, scopes, accessLevel)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupAccessToken")
	}

	var r0 *token0.TokenGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) (*token0.TokenGroup, error)); ok {
		return returnFunc(ctx, groupId, name, expiresAt, scopes, accessLevel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) *token0.TokenGroup); ok {
		r0 = returnFunc(ctx, groupId, name, expiresAt, scopes, accessLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) error); ok {
		r1 = returnFunc(ctx, groupId, name, expiresAt, scopes, accessLevel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateGroupAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupAccessToken'
type MockClient_CreateGroupAccessToken_Call struct {
	*mock.Call
}

// CreateGroupAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId string
//   - name string
//   - expiresAt time.Time
//   - scopes []string
//   - accessLevel token.AccessLevel
func (_e *MockClient_Expecter) CreateGroupAccessToken(ctx interface{}, groupId interface{}, name interface{}, expiresAt interface{}, scopes interface{}, accessLevel interface{}) *MockClient_CreateGroupAccessToken_Call {
	return &MockClient_CreateGroupAccessToken_Call{Call: _e.mock.On("CreateGroupAccessToken", ctx, groupId, name, expiresAt, scopes, accessLevel)}
}

func (_c *MockClient_CreateGroupAccessToken_Call) Run(run func(ctx context.Context, groupId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel)) *MockClient_CreateGroupAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 token.AccessLevel
		if args[5] != nil {
			arg5 = args[5].(token.AccessLevel)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateGroupAccessToken_Call) Return(tokenGroup *token0.TokenGroup, err error) *MockClient_CreateGroupAccessToken_Call {
	_c.Call.Return(tokenGroup, err)
	return _c
}

func (_c *MockClient_CreateGroupAccessToken_Call) RunAndReturn(run func(ctx context.Context, groupId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel) (*token0.TokenGroup, error)) *MockClient_CreateGroupAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupDeployToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateGroupDeployToken(ctx context.Context, path string, groupId int64, name string, expiresAt *time.Time, scopes []string) (*token0.TokenGroupDeploy, error) {
	ret := _mock.Called(ctx, path, groupId, name, expiresAt, scopes)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupDeployToken")
	}

	var r0 *token0.TokenGroupDeploy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, *time.Time, []string) (*token0.TokenGroupDeploy, error)); ok {
		return returnFunc(ctx, path, groupId, name, expiresAt, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, *time.Time, []string) *token0.TokenGroupDeploy); ok {
		r0 = returnFunc(ctx, path, groupId, name, expiresAt, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenGroupDeploy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string, *time.Time, []string) error); ok {
		r1 = returnFunc(ctx, path, groupId, name, expiresAt, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateGroupDeployToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupDeployToken'
type MockClient_CreateGroupDeployToken_Call struct {
	*mock.Call
}

// CreateGroupDeployToken is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - groupId int64
//   - name string
//   - expiresAt *time.Time
//   - scopes []string
func (_e *MockClient_Expecter) CreateGroupDeployToken(ctx interface{}, path interface{}, groupId interface{}, name interface{}, expiresAt interface{}, scopes interface{}) *MockClient_CreateGroupDeployToken_Call {
	return &MockClient_CreateGroupDeployToken_Call{Call: _e.mock.On("CreateGroupDeployToken", ctx, path, groupId, name, expiresAt, scopes)}
}

func (_c *MockClient_CreateGroupDeployToken_Call) Run(run func(ctx context.Context, path string, groupId int64, name string, expiresAt *time.Time, scopes []string)) *MockClient_CreateGroupDeployToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateGroupDeployToken_Call) Return(et *token0.TokenGroupDeploy, err error) *MockClient_CreateGroupDeployToken_Call {
	_c.Call.Return(et, err)
	return _c
}

func (_c *MockClient_CreateGroupDeployToken_Call) RunAndReturn(run func(ctx context.Context, path string, groupId int64, name string, expiresAt *time.Time, scopes []string) (*token0.TokenGroupDeploy, error)) *MockClient_CreateGroupDeployToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupServiceAccountAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateGroupServiceAccountAccessToken(ctx context.Context, group string, groupId string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenGroupServiceAccount, error) {
	ret := _mock.Called(ctx, group, groupId, userId, name, expiresAt, scopes)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupServiceAccountAccessToken")
	}

	var r0 *token0.TokenGroupServiceAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, time.Time, []string) (*token0.TokenGroupServiceAccount, error)); ok {
		return returnFunc(ctx, group, groupId, userId, name, expiresAt, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, time.Time, []string) *token0.TokenGroupServiceAccount); ok {
		r0 = returnFunc(ctx, group, groupId, userId, name, expiresAt, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenGroupServiceAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, string, time.Time, []string) error); ok {
		r1 = returnFunc(ctx, group, groupId, userId, name, expiresAt, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateGroupServiceAccountAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupServiceAccountAccessToken'
type MockClient_CreateGroupServiceAccountAccessToken_Call struct {
	*mock.Call
}

// CreateGroupServiceAccountAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - group string
//   - groupId string
//   - userId int64
//   - name string
//   - expiresAt time.Time
//   - scopes []string
func (_e *MockClient_Expecter) CreateGroupServiceAccountAccessToken(ctx interface{}, group interface{}, groupId interface{}, userId interface{}, name interface{}, expiresAt interface{}, scopes interface{}) *MockClient_CreateGroupServiceAccountAccessToken_Call {
	return &MockClient_CreateGroupServiceAccountAccessToken_Call{Call: _e.mock.On("CreateGroupServiceAccountAccessToken", ctx, group, groupId, userId, name, expiresAt, scopes)}
}

func (_c *MockClient_CreateGroupServiceAccountAccessToken_Call) Run(run func(ctx context.Context, group string, groupId string, userId int64, name string, expiresAt time.Time, scopes []string)) *MockClient_CreateGroupServiceAccountAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		var arg6 []string
		if args[6] != nil {
			arg6 = args[6].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockClient_CreateGroupServiceAccountAccessToken_Call) Return(tokenGroupServiceAccount *token0.TokenGroupServiceAccount, err error) *MockClient_CreateGroupServiceAccountAccessToken_Call {
	_c.Call.Return(tokenGroupServiceAccount, err)
	return _c
}

func (_c *MockClient_CreateGroupServiceAccountAccessToken_Call) RunAndReturn(run func(ctx context.Context, group string, groupId string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenGroupServiceAccount, error)) *MockClient_CreateGroupServiceAccountAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePersonalAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreatePersonalAccessToken(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenPersonal, error) {
	ret := _mock.Called(ctx, username, userId, name, expiresAt, scopes)

	if len(ret) == 0 {
		panic("no return value specified for CreatePersonalAccessToken")
	}

	var r0 *token0.TokenPersonal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, time.Time, []string) (*token0.TokenPersonal, error)); ok {
		return returnFunc(ctx, username, userId, name, expiresAt, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, time.Time, []string) *token0.TokenPersonal); ok {
		r0 = returnFunc(ctx, username, userId, name, expiresAt, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenPersonal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string, time.Time, []string) error); ok {
		r1 = returnFunc(ctx, username, userId, name, expiresAt, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreatePersonalAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePersonalAccessToken'
type MockClient_CreatePersonalAccessToken_Call struct {
	*mock.Call
}

// CreatePersonalAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - userId int64
//   - name string
//   - expiresAt time.Time
//   - scopes []string
func (_e *MockClient_Expecter) CreatePersonalAccessToken(ctx interface{}, username interface{}, userId interface{}, name interface{}, expiresAt interface{}, scopes interface{}) *MockClient_CreatePersonalAccessToken_Call {
	return &MockClient_CreatePersonalAccessToken_Call{Call: _e.mock.On("CreatePersonalAccessToken", ctx, username, userId, name, expiresAt, scopes)}
}

func (_c *MockClient_CreatePersonalAccessToken_Call) Run(run func(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string)) *MockClient_CreatePersonalAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreatePersonalAccessToken_Call) Return(tokenPersonal *token0.TokenPersonal, err error) *MockClient_CreatePersonalAccessToken_Call {
	_c.Call.Return(tokenPersonal, err)
	return _c
}

func (_c *MockClient_CreatePersonalAccessToken_Call) RunAndReturn(run func(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenPersonal, error)) *MockClient_CreatePersonalAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePipelineProjectTriggerAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreatePipelineProjectTriggerAccessToken(ctx context.Context, path string, name string, projectId int64, description string, expiresAt *time.Time) (*token0.TokenPipelineProjectTrigger, error) {
	ret := _mock.Called(ctx, path, name, projectId, description, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CreatePipelineProjectTriggerAccessToken")
	}

	var r0 *token0.TokenPipelineProjectTrigger
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, *time.Time) (*token0.TokenPipelineProjectTrigger, error)); ok {
		return returnFunc(ctx, path, name, projectId, description, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, string, *time.Time) *token0.TokenPipelineProjectTrigger); ok {
		r0 = returnFunc(ctx, path, name, projectId, description, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenPipelineProjectTrigger)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, string, *time.Time) error); ok {
		r1 = returnFunc(ctx, path, name, projectId, description, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreatePipelineProjectTriggerAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePipelineProjectTriggerAccessToken'
type MockClient_CreatePipelineProjectTriggerAccessToken_Call struct {
	*mock.Call
}

// CreatePipelineProjectTriggerAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - name string
//   - projectId int64
//   - description string
//   - expiresAt *time.Time
func (_e *MockClient_Expecter) CreatePipelineProjectTriggerAccessToken(ctx interface{}, path interface{}, name interface{}, projectId interface{}, description interface{}, expiresAt interface{}) *MockClient_CreatePipelineProjectTriggerAccessToken_Call {
	return &MockClient_CreatePipelineProjectTriggerAccessToken_Call{Call: _e.mock.On("CreatePipelineProjectTriggerAccessToken", ctx, path, name, projectId, description, expiresAt)}
}

func (_c *MockClient_CreatePipelineProjectTriggerAccessToken_Call) Run(run func(ctx context.Context, path string, name string, projectId int64, description string, expiresAt *time.Time)) *MockClient_CreatePipelineProjectTriggerAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreatePipelineProjectTriggerAccessToken_Call) Return(tokenPipelineProjectTrigger *token0.TokenPipelineProjectTrigger, err error) *MockClient_CreatePipelineProjectTriggerAccessToken_Call {
	_c.Call.Return(tokenPipelineProjectTrigger, err)
	return _c
}

func (_c *MockClient_CreatePipelineProjectTriggerAccessToken_Call) RunAndReturn(run func(ctx context.Context, path string, name string, projectId int64, description string, expiresAt *time.Time) (*token0.TokenPipelineProjectTrigger, error)) *MockClient_CreatePipelineProjectTriggerAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProjectAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateProjectAccessToken(ctx context.Context, projectId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel) (*token0.TokenProject, error) {
	ret := _mock.Called(ctx, projectId, name, expiresAt, scopes, accessLevel)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectAccessToken")
	}

	var r0 *token0.TokenProject
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) (*token0.TokenProject, error)); ok {
		return returnFunc(ctx, projectId, name, expiresAt, scopes, accessLevel)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) *token0.TokenProject); ok {
		r0 = returnFunc(ctx, projectId, name, expiresAt, scopes, accessLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenProject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time, []string, token.AccessLevel) error); ok {
		r1 = returnFunc(ctx, projectId, name, expiresAt, scopes, accessLevel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateProjectAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectAccessToken'
type MockClient_CreateProjectAccessToken_Call struct {
	*mock.Call
}

// CreateProjectAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId string
//   - name string
//   - expiresAt time.Time
//   - scopes []string
//   - accessLevel token.AccessLevel
func (_e *MockClient_Expecter) CreateProjectAccessToken(ctx interface{}, projectId interface{}, name interface{}, expiresAt interface{}, scopes interface{}, accessLevel interface{}) *MockClient_CreateProjectAccessToken_Call {
	return &MockClient_CreateProjectAccessToken_Call{Call: _e.mock.On("CreateProjectAccessToken", ctx, projectId, name, expiresAt, scopes, accessLevel)}
}

func (_c *MockClient_CreateProjectAccessToken_Call) Run(run func(ctx context.Context, projectId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel)) *MockClient_CreateProjectAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 token.AccessLevel
		if args[5] != nil {
			arg5 = args[5].(token.AccessLevel)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateProjectAccessToken_Call) Return(tokenProject *token0.TokenProject, err error) *MockClient_CreateProjectAccessToken_Call {
	_c.Call.Return(tokenProject, err)
	return _c
}

func (_c *MockClient_CreateProjectAccessToken_Call) RunAndReturn(run func(ctx context.Context, projectId string, name string, expiresAt time.Time, scopes []string, accessLevel token.AccessLevel) (*token0.TokenProject, error)) *MockClient_CreateProjectAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProjectDeployToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateProjectDeployToken(ctx context.Context, path string, projectId int64, name string, expiresAt *time.Time, scopes []string) (*token0.TokenProjectDeploy, error) {
	ret := _mock.Called(ctx, path, projectId, name, expiresAt, scopes)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectDeployToken")
	}

	var r0 *token0.TokenProjectDeploy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, *time.Time, []string) (*token0.TokenProjectDeploy, error)); ok {
		return returnFunc(ctx, path, projectId, name, expiresAt, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, *time.Time, []string) *token0.TokenProjectDeploy); ok {
		r0 = returnFunc(ctx, path, projectId, name, expiresAt, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenProjectDeploy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string, *time.Time, []string) error); ok {
		r1 = returnFunc(ctx, path, projectId, name, expiresAt, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateProjectDeployToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectDeployToken'
type MockClient_CreateProjectDeployToken_Call struct {
	*mock.Call
}

// CreateProjectDeployToken is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
//   - projectId int64
//   - name string
//   - expiresAt *time.Time
//   - scopes []string
func (_e *MockClient_Expecter) CreateProjectDeployToken(ctx interface{}, path interface{}, projectId interface{}, name interface{}, expiresAt interface{}, scopes interface{}) *MockClient_CreateProjectDeployToken_Call {
	return &MockClient_CreateProjectDeployToken_Call{Call: _e.mock.On("CreateProjectDeployToken", ctx, path, projectId, name, expiresAt, scopes)}
}

func (_c *MockClient_CreateProjectDeployToken_Call) Run(run func(ctx context.Context, path string, projectId int64, name string, expiresAt *time.Time, scopes []string)) *MockClient_CreateProjectDeployToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateProjectDeployToken_Call) Return(et *token0.TokenProjectDeploy, err error) *MockClient_CreateProjectDeployToken_Call {
	_c.Call.Return(et, err)
	return _c
}

func (_c *MockClient_CreateProjectDeployToken_Call) RunAndReturn(run func(ctx context.Context, path string, projectId int64, name string, expiresAt *time.Time, scopes []string) (*token0.TokenProjectDeploy, error)) *MockClient_CreateProjectDeployToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserServiceAccountAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) CreateUserServiceAccountAccessToken(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenUserServiceAccount, error) {
	ret := _mock.Called(ctx, username, userId, name, expiresAt, scopes)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserServiceAccountAccessToken")
	}

	var r0 *token0.TokenUserServiceAccount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, time.Time, []string) (*token0.TokenUserServiceAccount, error)); ok {
		return returnFunc(ctx, username, userId, name, expiresAt, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string, time.Time, []string) *token0.TokenUserServiceAccount); ok {
		r0 = returnFunc(ctx, username, userId, name, expiresAt, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenUserServiceAccount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, string, time.Time, []string) error); ok {
		r1 = returnFunc(ctx, username, userId, name, expiresAt, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateUserServiceAccountAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserServiceAccountAccessToken'
type MockClient_CreateUserServiceAccountAccessToken_Call struct {
	*mock.Call
}

// CreateUserServiceAccountAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - userId int64
//   - name string
//   - expiresAt time.Time
//   - scopes []string
func (_e *MockClient_Expecter) CreateUserServiceAccountAccessToken(ctx interface{}, username interface{}, userId interface{}, name interface{}, expiresAt interface{}, scopes interface{}) *MockClient_CreateUserServiceAccountAccessToken_Call {
	return &MockClient_CreateUserServiceAccountAccessToken_Call{Call: _e.mock.On("CreateUserServiceAccountAccessToken", ctx, username, userId, name, expiresAt, scopes)}
}

func (_c *MockClient_CreateUserServiceAccountAccessToken_Call) Run(run func(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string)) *MockClient_CreateUserServiceAccountAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_CreateUserServiceAccountAccessToken_Call) Return(tokenUserServiceAccount *token0.TokenUserServiceAccount, err error) *MockClient_CreateUserServiceAccountAccessToken_Call {
	_c.Call.Return(tokenUserServiceAccount, err)
	return _c
}

func (_c *MockClient_CreateUserServiceAccountAccessToken_Call) RunAndReturn(run func(ctx context.Context, username string, userId int64, name string, expiresAt time.Time, scopes []string) (*token0.TokenUserServiceAccount, error)) *MockClient_CreateUserServiceAccountAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentTokenInfo provides a mock function for the type MockClient
func (_mock *MockClient) CurrentTokenInfo(ctx context.Context) (*token0.TokenConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CurrentTokenInfo")
	}

	var r0 *token0.TokenConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*token0.TokenConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *token0.TokenConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CurrentTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentTokenInfo'
type MockClient_CurrentTokenInfo_Call struct {
	*mock.Call
}

// CurrentTokenInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) CurrentTokenInfo(ctx interface{}) *MockClient_CurrentTokenInfo_Call {
	return &MockClient_CurrentTokenInfo_Call{Call: _e.mock.On("CurrentTokenInfo", ctx)}
}

func (_c *MockClient_CurrentTokenInfo_Call) Run(run func(ctx context.Context)) *MockClient_CurrentTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_CurrentTokenInfo_Call) Return(tokenConfig *token0.TokenConfig, err error) *MockClient_CurrentTokenInfo_Call {
	_c.Call.Return(tokenConfig, err)
	return _c
}

func (_c *MockClient_CurrentTokenInfo_Call) RunAndReturn(run func(ctx context.Context) (*token0.TokenConfig, error)) *MockClient_CurrentTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupIdByPath provides a mock function for the type MockClient
func (_mock *MockClient) GetGroupIdByPath(ctx context.Context, path string) (int64, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupIdByPath")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetGroupIdByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupIdByPath'
type MockClient_GetGroupIdByPath_Call struct {
	*mock.Call
}

// GetGroupIdByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockClient_Expecter) GetGroupIdByPath(ctx interface{}, path interface{}) *MockClient_GetGroupIdByPath_Call {
	return &MockClient_GetGroupIdByPath_Call{Call: _e.mock.On("GetGroupIdByPath", ctx, path)}
}

func (_c *MockClient_GetGroupIdByPath_Call) Run(run func(ctx context.Context, path string)) *MockClient_GetGroupIdByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetGroupIdByPath_Call) Return(n int64, err error) *MockClient_GetGroupIdByPath_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClient_GetGroupIdByPath_Call) RunAndReturn(run func(ctx context.Context, path string) (int64, error)) *MockClient_GetGroupIdByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectIdByPath provides a mock function for the type MockClient
func (_mock *MockClient) GetProjectIdByPath(ctx context.Context, path string) (int64, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectIdByPath")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetProjectIdByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectIdByPath'
type MockClient_GetProjectIdByPath_Call struct {
	*mock.Call
}

// GetProjectIdByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockClient_Expecter) GetProjectIdByPath(ctx interface{}, path interface{}) *MockClient_GetProjectIdByPath_Call {
	return &MockClient_GetProjectIdByPath_Call{Call: _e.mock.On("GetProjectIdByPath", ctx, path)}
}

func (_c *MockClient_GetProjectIdByPath_Call) Run(run func(ctx context.Context, path string)) *MockClient_GetProjectIdByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetProjectIdByPath_Call) Return(n int64, err error) *MockClient_GetProjectIdByPath_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClient_GetProjectIdByPath_Call) RunAndReturn(run func(ctx context.Context, path string) (int64, error)) *MockClient_GetProjectIdByPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserIdByUsername provides a mock function for the type MockClient
func (_mock *MockClient) GetUserIdByUsername(ctx context.Context, username string) (int64, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIdByUsername")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserIdByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIdByUsername'
type MockClient_GetUserIdByUsername_Call struct {
	*mock.Call
}

// GetUserIdByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockClient_Expecter) GetUserIdByUsername(ctx interface{}, username interface{}) *MockClient_GetUserIdByUsername_Call {
	return &MockClient_GetUserIdByUsername_Call{Call: _e.mock.On("GetUserIdByUsername", ctx, username)}
}

func (_c *MockClient_GetUserIdByUsername_Call) Run(run func(ctx context.Context, username string)) *MockClient_GetUserIdByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserIdByUsername_Call) Return(n int64, err error) *MockClient_GetUserIdByUsername_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockClient_GetUserIdByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (int64, error)) *MockClient_GetUserIdByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GitlabClient provides a mock function for the type MockClient
func (_mock *MockClient) GitlabClient(ctx context.Context) *gitlab.Client {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GitlabClient")
	}

	var r0 *gitlab.Client
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gitlab.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Client)
		}
	}
	return r0
}

// MockClient_GitlabClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GitlabClient'
type MockClient_GitlabClient_Call struct {
	*mock.Call
}

// GitlabClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GitlabClient(ctx interface{}) *MockClient_GitlabClient_Call {
	return &MockClient_GitlabClient_Call{Call: _e.mock.On("GitlabClient", ctx)}
}

func (_c *MockClient_GitlabClient_Call) Run(run func(ctx context.Context)) *MockClient_GitlabClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GitlabClient_Call) Return(client *gitlab.Client) *MockClient_GitlabClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClient_GitlabClient_Call) RunAndReturn(run func(ctx context.Context) *gitlab.Client) *MockClient_GitlabClient_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockClient
func (_mock *MockClient) Metadata(ctx context.Context) (*gitlab.Metadata, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 *gitlab.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gitlab.Metadata, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gitlab.Metadata); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Metadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockClient_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Metadata(ctx interface{}) *MockClient_Metadata_Call {
	return &MockClient_Metadata_Call{Call: _e.mock.On("Metadata", ctx)}
}

func (_c *MockClient_Metadata_Call) Run(run func(ctx context.Context)) *MockClient_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Metadata_Call) Return(metadata *gitlab.Metadata, err error) *MockClient_Metadata_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockClient_Metadata_Call) RunAndReturn(run func(ctx context.Context) (*gitlab.Metadata, error)) *MockClient_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeGroupAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeGroupAccessToken(ctx context.Context, tokenId int64, groupId string) error {
	ret := _mock.Called(ctx, tokenId, groupId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeGroupAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, tokenId, groupId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeGroupAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeGroupAccessToken'
type MockClient_RevokeGroupAccessToken_Call struct {
	*mock.Call
}

// RevokeGroupAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenId int64
//   - groupId string
func (_e *MockClient_Expecter) RevokeGroupAccessToken(ctx interface{}, tokenId interface{}, groupId interface{}) *MockClient_RevokeGroupAccessToken_Call {
	return &MockClient_RevokeGroupAccessToken_Call{Call: _e.mock.On("RevokeGroupAccessToken", ctx, tokenId, groupId)}
}

func (_c *MockClient_RevokeGroupAccessToken_Call) Run(run func(ctx context.Context, tokenId int64, groupId string)) *MockClient_RevokeGroupAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RevokeGroupAccessToken_Call) Return(err error) *MockClient_RevokeGroupAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeGroupAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenId int64, groupId string) error) *MockClient_RevokeGroupAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeGroupDeployToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeGroupDeployToken(ctx context.Context, groupId int64, deployTokenId int64) error {
	ret := _mock.Called(ctx, groupId, deployTokenId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeGroupDeployToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, groupId, deployTokenId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeGroupDeployToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeGroupDeployToken'
type MockClient_RevokeGroupDeployToken_Call struct {
	*mock.Call
}

// RevokeGroupDeployToken is a helper method to define mock.On call
//   - ctx context.Context
//   - groupId int64
//   - deployTokenId int64
func (_e *MockClient_Expecter) RevokeGroupDeployToken(ctx interface{}, groupId interface{}, deployTokenId interface{}) *MockClient_RevokeGroupDeployToken_Call {
	return &MockClient_RevokeGroupDeployToken_Call{Call: _e.mock.On("RevokeGroupDeployToken", ctx, groupId, deployTokenId)}
}

func (_c *MockClient_RevokeGroupDeployToken_Call) Run(run func(ctx context.Context, groupId int64, deployTokenId int64)) *MockClient_RevokeGroupDeployToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RevokeGroupDeployToken_Call) Return(err error) *MockClient_RevokeGroupDeployToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeGroupDeployToken_Call) RunAndReturn(run func(ctx context.Context, groupId int64, deployTokenId int64) error) *MockClient_RevokeGroupDeployToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeGroupServiceAccountAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeGroupServiceAccountAccessToken(ctx context.Context, token1 string) error {
	ret := _mock.Called(ctx, token1)

	if len(ret) == 0 {
		panic("no return value specified for RevokeGroupServiceAccountAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeGroupServiceAccountAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeGroupServiceAccountAccessToken'
type MockClient_RevokeGroupServiceAccountAccessToken_Call struct {
	*mock.Call
}

// RevokeGroupServiceAccountAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token1 string
func (_e *MockClient_Expecter) RevokeGroupServiceAccountAccessToken(ctx interface{}, token1 interface{}) *MockClient_RevokeGroupServiceAccountAccessToken_Call {
	return &MockClient_RevokeGroupServiceAccountAccessToken_Call{Call: _e.mock.On("RevokeGroupServiceAccountAccessToken", ctx, token1)}
}

func (_c *MockClient_RevokeGroupServiceAccountAccessToken_Call) Run(run func(ctx context.Context, token1 string)) *MockClient_RevokeGroupServiceAccountAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RevokeGroupServiceAccountAccessToken_Call) Return(err error) *MockClient_RevokeGroupServiceAccountAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeGroupServiceAccountAccessToken_Call) RunAndReturn(run func(ctx context.Context, token1 string) error) *MockClient_RevokeGroupServiceAccountAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePersonalAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokePersonalAccessToken(ctx context.Context, tokenId int64) error {
	ret := _mock.Called(ctx, tokenId)

	if len(ret) == 0 {
		panic("no return value specified for RevokePersonalAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, tokenId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokePersonalAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePersonalAccessToken'
type MockClient_RevokePersonalAccessToken_Call struct {
	*mock.Call
}

// RevokePersonalAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenId int64
func (_e *MockClient_Expecter) RevokePersonalAccessToken(ctx interface{}, tokenId interface{}) *MockClient_RevokePersonalAccessToken_Call {
	return &MockClient_RevokePersonalAccessToken_Call{Call: _e.mock.On("RevokePersonalAccessToken", ctx, tokenId)}
}

func (_c *MockClient_RevokePersonalAccessToken_Call) Run(run func(ctx context.Context, tokenId int64)) *MockClient_RevokePersonalAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RevokePersonalAccessToken_Call) Return(err error) *MockClient_RevokePersonalAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokePersonalAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenId int64) error) *MockClient_RevokePersonalAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokePipelineProjectTriggerAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokePipelineProjectTriggerAccessToken(ctx context.Context, projectId int64, tokenId int64) error {
	ret := _mock.Called(ctx, projectId, tokenId)

	if len(ret) == 0 {
		panic("no return value specified for RevokePipelineProjectTriggerAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, projectId, tokenId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokePipelineProjectTriggerAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokePipelineProjectTriggerAccessToken'
type MockClient_RevokePipelineProjectTriggerAccessToken_Call struct {
	*mock.Call
}

// RevokePipelineProjectTriggerAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId int64
//   - tokenId int64
func (_e *MockClient_Expecter) RevokePipelineProjectTriggerAccessToken(ctx interface{}, projectId interface{}, tokenId interface{}) *MockClient_RevokePipelineProjectTriggerAccessToken_Call {
	return &MockClient_RevokePipelineProjectTriggerAccessToken_Call{Call: _e.mock.On("RevokePipelineProjectTriggerAccessToken", ctx, projectId, tokenId)}
}

func (_c *MockClient_RevokePipelineProjectTriggerAccessToken_Call) Run(run func(ctx context.Context, projectId int64, tokenId int64)) *MockClient_RevokePipelineProjectTriggerAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RevokePipelineProjectTriggerAccessToken_Call) Return(err error) *MockClient_RevokePipelineProjectTriggerAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokePipelineProjectTriggerAccessToken_Call) RunAndReturn(run func(ctx context.Context, projectId int64, tokenId int64) error) *MockClient_RevokePipelineProjectTriggerAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeProjectAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeProjectAccessToken(ctx context.Context, tokenId int64, projectId string) error {
	ret := _mock.Called(ctx, tokenId, projectId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeProjectAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, tokenId, projectId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeProjectAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeProjectAccessToken'
type MockClient_RevokeProjectAccessToken_Call struct {
	*mock.Call
}

// RevokeProjectAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenId int64
//   - projectId string
func (_e *MockClient_Expecter) RevokeProjectAccessToken(ctx interface{}, tokenId interface{}, projectId interface{}) *MockClient_RevokeProjectAccessToken_Call {
	return &MockClient_RevokeProjectAccessToken_Call{Call: _e.mock.On("RevokeProjectAccessToken", ctx, tokenId, projectId)}
}

func (_c *MockClient_RevokeProjectAccessToken_Call) Run(run func(ctx context.Context, tokenId int64, projectId string)) *MockClient_RevokeProjectAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RevokeProjectAccessToken_Call) Return(err error) *MockClient_RevokeProjectAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeProjectAccessToken_Call) RunAndReturn(run func(ctx context.Context, tokenId int64, projectId string) error) *MockClient_RevokeProjectAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeProjectDeployToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeProjectDeployToken(ctx context.Context, projectId int64, deployTokenId int64) error {
	ret := _mock.Called(ctx, projectId, deployTokenId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeProjectDeployToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, projectId, deployTokenId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeProjectDeployToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeProjectDeployToken'
type MockClient_RevokeProjectDeployToken_Call struct {
	*mock.Call
}

// RevokeProjectDeployToken is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId int64
//   - deployTokenId int64
func (_e *MockClient_Expecter) RevokeProjectDeployToken(ctx interface{}, projectId interface{}, deployTokenId interface{}) *MockClient_RevokeProjectDeployToken_Call {
	return &MockClient_RevokeProjectDeployToken_Call{Call: _e.mock.On("RevokeProjectDeployToken", ctx, projectId, deployTokenId)}
}

func (_c *MockClient_RevokeProjectDeployToken_Call) Run(run func(ctx context.Context, projectId int64, deployTokenId int64)) *MockClient_RevokeProjectDeployToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RevokeProjectDeployToken_Call) Return(err error) *MockClient_RevokeProjectDeployToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeProjectDeployToken_Call) RunAndReturn(run func(ctx context.Context, projectId int64, deployTokenId int64) error) *MockClient_RevokeProjectDeployToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeUserServiceAccountAccessToken provides a mock function for the type MockClient
func (_mock *MockClient) RevokeUserServiceAccountAccessToken(ctx context.Context, token1 string) error {
	ret := _mock.Called(ctx, token1)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserServiceAccountAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RevokeUserServiceAccountAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserServiceAccountAccessToken'
type MockClient_RevokeUserServiceAccountAccessToken_Call struct {
	*mock.Call
}

// RevokeUserServiceAccountAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token1 string
func (_e *MockClient_Expecter) RevokeUserServiceAccountAccessToken(ctx interface{}, token1 interface{}) *MockClient_RevokeUserServiceAccountAccessToken_Call {
	return &MockClient_RevokeUserServiceAccountAccessToken_Call{Call: _e.mock.On("RevokeUserServiceAccountAccessToken", ctx, token1)}
}

func (_c *MockClient_RevokeUserServiceAccountAccessToken_Call) Run(run func(ctx context.Context, token1 string)) *MockClient_RevokeUserServiceAccountAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RevokeUserServiceAccountAccessToken_Call) Return(err error) *MockClient_RevokeUserServiceAccountAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RevokeUserServiceAccountAccessToken_Call) RunAndReturn(run func(ctx context.Context, token1 string) error) *MockClient_RevokeUserServiceAccountAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RotateCurrentToken provides a mock function for the type MockClient
func (_mock *MockClient) RotateCurrentToken(ctx context.Context) (*token0.TokenConfig, *token0.TokenConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RotateCurrentToken")
	}

	var r0 *token0.TokenConfig
	var r1 *token0.TokenConfig
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*token0.TokenConfig, *token0.TokenConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *token0.TokenConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token0.TokenConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *token0.TokenConfig); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*token0.TokenConfig)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockClient_RotateCurrentToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateCurrentToken'
type MockClient_RotateCurrentToken_Call struct {
	*mock.Call
}

// RotateCurrentToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) RotateCurrentToken(ctx interface{}) *MockClient_RotateCurrentToken_Call {
	return &MockClient_RotateCurrentToken_Call{Call: _e.mock.On("RotateCurrentToken", ctx)}
}

func (_c *MockClient_RotateCurrentToken_Call) Run(run func(ctx context.Context)) *MockClient_RotateCurrentToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_RotateCurrentToken_Call) Return(newToken *token0.TokenConfig, oldToken *token0.TokenConfig, err error) *MockClient_RotateCurrentToken_Call {
	_c.Call.Return(newToken, oldToken, err)
	return _c
}

func (_c *MockClient_RotateCurrentToken_Call) RunAndReturn(run func(ctx context.Context) (*token0.TokenConfig, *token0.TokenConfig, error)) *MockClient_RotateCurrentToken_Call {
	_c.Call.Return(run)
	return _c
}

// Valid provides a mock function for the type MockClient
func (_mock *MockClient) Valid(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClient_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockClient_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Valid(ctx interface{}) *MockClient_Valid_Call {
	return &MockClient_Valid_Call{Call: _e.mock.On("Valid", ctx)}
}

func (_c *MockClient_Valid_Call) Run(run func(ctx context.Context)) *MockClient_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Valid_Call) Return(b bool) *MockClient_Valid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClient_Valid_Call) RunAndReturn(run func(ctx context.Context) bool) *MockClient_Valid_Call {
	_c.Call.Return(run)
	return _c
}
