// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
	"github.com/ilijamt/vault-plugin-secrets-gitlab/internal/event"
	"github.com/ilijamt/vault-plugin-secrets-gitlab/internal/flags"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFlagsProvider creates a new instance of MockFlagsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlagsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlagsProvider {
	mock := &MockFlagsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlagsProvider is an autogenerated mock type for the FlagsProvider type
type MockFlagsProvider struct {
	mock.Mock
}

type MockFlagsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlagsProvider) EXPECT() *MockFlagsProvider_Expecter {
	return &MockFlagsProvider_Expecter{mock: &_m.Mock}
}

// Flags provides a mock function for the type MockFlagsProvider
func (_mock *MockFlagsProvider) Flags() flags.Flags {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Flags")
	}

	var r0 flags.Flags
	if returnFunc, ok := ret.Get(0).(func() flags.Flags); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(flags.Flags)
	}
	return r0
}

// MockFlagsProvider_Flags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flags'
type MockFlagsProvider_Flags_Call struct {
	*mock.Call
}

// Flags is a helper method to define mock.On call
func (_e *MockFlagsProvider_Expecter) Flags() *MockFlagsProvider_Flags_Call {
	return &MockFlagsProvider_Flags_Call{Call: _e.mock.On("Flags")}
}

func (_c *MockFlagsProvider_Flags_Call) Run(run func()) *MockFlagsProvider_Flags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFlagsProvider_Flags_Call) Return(flags1 flags.Flags) *MockFlagsProvider_Flags_Call {
	_c.Call.Return(flags1)
	return _c
}

func (_c *MockFlagsProvider_Flags_Call) RunAndReturn(run func() flags.Flags) *MockFlagsProvider_Flags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlags provides a mock function for the type MockFlagsProvider
func (_mock *MockFlagsProvider) UpdateFlags(fn func(*flags.Flags)) {
	_mock.Called(fn)
	return
}

// MockFlagsProvider_UpdateFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlags'
type MockFlagsProvider_UpdateFlags_Call struct {
	*mock.Call
}

// UpdateFlags is a helper method to define mock.On call
//   - fn func(*flags.Flags)
func (_e *MockFlagsProvider_Expecter) UpdateFlags(fn interface{}) *MockFlagsProvider_UpdateFlags_Call {
	return &MockFlagsProvider_UpdateFlags_Call{Call: _e.mock.On("UpdateFlags", fn)}
}

func (_c *MockFlagsProvider_UpdateFlags_Call) Run(run func(fn func(*flags.Flags))) *MockFlagsProvider_UpdateFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*flags.Flags)
		if args[0] != nil {
			arg0 = args[0].(func(*flags.Flags))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlagsProvider_UpdateFlags_Call) Return() *MockFlagsProvider_UpdateFlags_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFlagsProvider_UpdateFlags_Call) RunAndReturn(run func(fn func(*flags.Flags))) *MockFlagsProvider_UpdateFlags_Call {
	_c.Run(run)
	return _c
}

// NewMockEventSender creates a new instance of MockEventSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSender {
	mock := &MockEventSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSender is an autogenerated mock type for the EventSender type
type MockEventSender struct {
	mock.Mock
}

type MockEventSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSender) EXPECT() *MockEventSender_Expecter {
	return &MockEventSender_Expecter{mock: &_m.Mock}
}

// SendEvent provides a mock function for the type MockEventSender
func (_mock *MockEventSender) SendEvent(ctx context.Context, eventType event.EventType, metadata map[string]string) error {
	ret := _mock.Called(ctx, eventType, metadata)

	if len(ret) == 0 {
		panic("no return value specified for SendEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, event.EventType, map[string]string) error); ok {
		r0 = returnFunc(ctx, eventType, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSender_SendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEvent'
type MockEventSender_SendEvent_Call struct {
	*mock.Call
}

// SendEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType event.EventType
//   - metadata map[string]string
func (_e *MockEventSender_Expecter) SendEvent(ctx interface{}, eventType interface{}, metadata interface{}) *MockEventSender_SendEvent_Call {
	return &MockEventSender_SendEvent_Call{Call: _e.mock.On("SendEvent", ctx, eventType, metadata)}
}

func (_c *MockEventSender_SendEvent_Call) Run(run func(ctx context.Context, eventType event.EventType, metadata map[string]string)) *MockEventSender_SendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 event.EventType
		if args[1] != nil {
			arg1 = args[1].(event.EventType)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventSender_SendEvent_Call) Return(err error) *MockEventSender_SendEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSender_SendEvent_Call) RunAndReturn(run func(ctx context.Context, eventType event.EventType, metadata map[string]string) error) *MockEventSender_SendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPathProvider creates a new instance of MockPathProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathProvider {
	mock := &MockPathProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPathProvider is an autogenerated mock type for the PathProvider type
type MockPathProvider struct {
	mock.Mock
}

type MockPathProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPathProvider) EXPECT() *MockPathProvider_Expecter {
	return &MockPathProvider_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockPathProvider
func (_mock *MockPathProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPathProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPathProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPathProvider_Expecter) Name() *MockPathProvider_Name_Call {
	return &MockPathProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPathProvider_Name_Call) Run(run func()) *MockPathProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPathProvider_Name_Call) Return(s string) *MockPathProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPathProvider_Name_Call) RunAndReturn(run func() string) *MockPathProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Paths provides a mock function for the type MockPathProvider
func (_mock *MockPathProvider) Paths() []*framework.Path {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Paths")
	}

	var r0 []*framework.Path
	if returnFunc, ok := ret.Get(0).(func() []*framework.Path); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*framework.Path)
		}
	}
	return r0
}

// MockPathProvider_Paths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Paths'
type MockPathProvider_Paths_Call struct {
	*mock.Call
}

// Paths is a helper method to define mock.On call
func (_e *MockPathProvider_Expecter) Paths() *MockPathProvider_Paths_Call {
	return &MockPathProvider_Paths_Call{Call: _e.mock.On("Paths")}
}

func (_c *MockPathProvider_Paths_Call) Run(run func()) *MockPathProvider_Paths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPathProvider_Paths_Call) Return(paths []*framework.Path) *MockPathProvider_Paths_Call {
	_c.Call.Return(paths)
	return _c
}

func (_c *MockPathProvider_Paths_Call) RunAndReturn(run func() []*framework.Path) *MockPathProvider_Paths_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPeriodicHandler creates a new instance of MockPeriodicHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeriodicHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeriodicHandler {
	mock := &MockPeriodicHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeriodicHandler is an autogenerated mock type for the PeriodicHandler type
type MockPeriodicHandler struct {
	mock.Mock
}

type MockPeriodicHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeriodicHandler) EXPECT() *MockPeriodicHandler_Expecter {
	return &MockPeriodicHandler_Expecter{mock: &_m.Mock}
}

// PeriodicFunc provides a mock function for the type MockPeriodicHandler
func (_mock *MockPeriodicHandler) PeriodicFunc(ctx context.Context, req *logical.Request) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PeriodicFunc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *logical.Request) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPeriodicHandler_PeriodicFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeriodicFunc'
type MockPeriodicHandler_PeriodicFunc_Call struct {
	*mock.Call
}

// PeriodicFunc is a helper method to define mock.On call
//   - ctx context.Context
//   - req *logical.Request
func (_e *MockPeriodicHandler_Expecter) PeriodicFunc(ctx interface{}, req interface{}) *MockPeriodicHandler_PeriodicFunc_Call {
	return &MockPeriodicHandler_PeriodicFunc_Call{Call: _e.mock.On("PeriodicFunc", ctx, req)}
}

func (_c *MockPeriodicHandler_PeriodicFunc_Call) Run(run func(ctx context.Context, req *logical.Request)) *MockPeriodicHandler_PeriodicFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *logical.Request
		if args[1] != nil {
			arg1 = args[1].(*logical.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPeriodicHandler_PeriodicFunc_Call) Return(err error) *MockPeriodicHandler_PeriodicFunc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPeriodicHandler_PeriodicFunc_Call) RunAndReturn(run func(ctx context.Context, req *logical.Request) error) *MockPeriodicHandler_PeriodicFunc_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvalidateHandler creates a new instance of MockInvalidateHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvalidateHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvalidateHandler {
	mock := &MockInvalidateHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInvalidateHandler is an autogenerated mock type for the InvalidateHandler type
type MockInvalidateHandler struct {
	mock.Mock
}

type MockInvalidateHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvalidateHandler) EXPECT() *MockInvalidateHandler_Expecter {
	return &MockInvalidateHandler_Expecter{mock: &_m.Mock}
}

// Invalidate provides a mock function for the type MockInvalidateHandler
func (_mock *MockInvalidateHandler) Invalidate(ctx context.Context, key string) {
	_mock.Called(ctx, key)
	return
}

// MockInvalidateHandler_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockInvalidateHandler_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockInvalidateHandler_Expecter) Invalidate(ctx interface{}, key interface{}) *MockInvalidateHandler_Invalidate_Call {
	return &MockInvalidateHandler_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, key)}
}

func (_c *MockInvalidateHandler_Invalidate_Call) Run(run func(ctx context.Context, key string)) *MockInvalidateHandler_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInvalidateHandler_Invalidate_Call) Return() *MockInvalidateHandler_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInvalidateHandler_Invalidate_Call) RunAndReturn(run func(ctx context.Context, key string)) *MockInvalidateHandler_Invalidate_Call {
	_c.Run(run)
	return _c
}
