template: testify
template-data:
  unroll-variadic: true
packages:
  # github.com/ilijamt/vault-plugin-secrets-gitlab/internal/gitlab:
  #   config:
  #     dir: internal/mocks
  #     pkgname: mocks
  #     filename: mock_gitlab.go
  #   interfaces:
  #     Client: {}
